### ISSUE TITLE
how can i use it after configure this project?

### ISSUE THREAD

**Issue by picturetxl** [recp/json#8]
when i generate .libs directory ,how can i use it to parse json? You said the project file is header
I use command : 
```c
gcc -shared -fPIC test_json.c -o test -L ./lib/libjson
```
to build c file. And I get an error
```
fatal error: common.h: No such file or directory
```

this is my code 
```c
#include "json/json.h"
#include "json/print.h"

int main(int argc, const char * argv[]) {
  json_doc_t *doc;
  json_t     *root;
  
  doc  = json_parse(/* JSON string */, true);
  root = doc->root;

  json_print_human(stderr, root);

  json_free(doc);

  return 0;
}
```

![image](https://user-images.githubusercontent.com/34642821/94576718-3d3b7480-02a8-11eb-8066-461f60ad8692.png)

**Comment by recp** [comment]
Hello @picturetxl 

You don't have to build this `json` library. Library offers two way to use, 1. Header-only, 2. Library-call.

`jsonc_` namespace is used for library-call functions and `json_` namespace is used for inline functions, if you use `json_` then building json itself is redundant. 

---

`common.h` must be exists in `include/json/common.h`, can you validate that? 

Did you copy json to your project directly? Otherwise, install script may have skipped `common.h` file which would be a build-bug.

**Comment by recp** [comment]
@picturetxl ping. Do you still have any issues?

**Comment by picturetxl** [comment]
thank you. It's all done.
